apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: create-and-read-ns-rolebinding
  namespace: final
subjects:
- kind: ServiceAccount
  name: clo835
  namespace: final
roleRef:
  kind: ClusterRole
  name: create-and-read-ns-role
  apiGroup: rbac.authorization.k8s.io
