kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: final
  name: create-and-read-ns-role
rules:
- apiGroups: [""] # "" indicates the core API group
  resources: ["namespace"]
  verbs: ["get","create"]