---
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: clo835-eks
  region: "us-east-1"
  version: "1.26"

availabilityZones: ["us-east-1a" ,"us-east-1b" ,"us-east-1c"]
iam:
  serviceRoleARN: arn:aws:iam::796109909635:role/LabRole
managedNodeGroups:
- name: workernode
  desiredCapacity: 2
  instanceType: t3.small
  ssh:
    enableSsm: true
  iam:
    instanceRoleARN: arn:aws:iam::796109909635:role/LabRole
    
---

apiVersion: v1
kind: Namespace
metadata:
  name: final