kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: mysql-pvc
  namespace: final
  annotations:
    volume.beta.kubernetes.io/storage-class: gp2
  labels:
    appname: clo835-final
spec:
  storageClassName: gp2
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi