apiVersion: v1
kind: Service
metadata:
  name: webapp-service
  namespace: final
  labels:
    app: clo835-final
spec:
  type: LoadBalancer
  selector:
    app: clo835-final
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 81