apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp
  namespace: final
  labels:
    app: employees
    component: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: employees
  template:
    metadata:
      labels:
        app: employees
        component: frontend
    spec:
      serviceAccountName: clo835
      containers:
        - name: app-container
          image: webapp:latest
          env:
            - name: DBPWD
              valueFrom:
                configMapKeyRef:
                  name: webapp-config
                  key: DBPWD
            - name: DBUSER
              valueFrom:
                configMapKeyRef:
                  name: webapp-config
                  key: DBUSER
            - name: DBHOST
              valueFrom:
                configMapKeyRef:
                  name: webapp-config
                  key: DBHOST
            - name: DBPORT
              valueFrom:
                configMapKeyRef:
                  name: webapp-config
                  key: DBPORT
          ports:
            - containerPort: 81
      imagePullSecrets:
        - name: imagepull-secret
